#!/bin/sh

if [ -z "${NARANJA_HOME}" ]
then
  echo "NARANJA_HOME is unset" 1>&2
  exit 1
fi

exec /usr/bin/env java \
-p "${NARANJA_HOME}/lib" \
-m com.io7m.naranja.cmdline/com.io7m.naranja.cmdline.NMain \
"$@"
